Add another source of cif file space group symmetry operations
glotzerlab/garnett pull request #141
Opened 2020-01-26 16:07 UTC by klarh

## Description
This PR makes the CIF reader check both the `_symmetry_equiv_pos_as_xyz` and `_space_group_symop_operation_xyz`. The latter is a different name for the same data, used in CIF files found in the [AFLOW Library of Crystallographic Prototypes](http://aflowlib.org/CrystalDatabase/index.html)

## Motivation and Context

Needed to read cif files from the AFLOW database listed above.

## How Has This Been Tested?

The change is minor, but has been tested on cif files from the AFLOW database.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds or improves functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/glotzerlab/garnett/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] I have updated the documentation (if relevant).
- [x] I have added tests that cover my changes (if relevant).
- [x] All new and existing tests passed.
- [x] I have updated the [credits](https://github.com/glotzerlab/garnett/blob/master/doc/credits.rst).
- [x] I have updated the [Changelog](https://github.com/glotzerlab/garnett/blob/master/changelog.rst).

2020-01-26 16:11 UTC, bdice requested changes
@klarh Can you add a test file? I'm not familiar with the CIF format. Also, are we using `pycifrw` to its fullest? I'm not clear on whether we're duplicating functionality that is present in `pycifrw` or not.

2020-01-26 16:33 UTC, klarh commented
@bdice I think the actual cif files I'm reading may be licensed GPL3, although I'm not 100% clear on that. I could duplicate the current cif file we have in the tests and just replace the string if you like, although that doesn't seem like a very useful test.

The CIF format is essentially a container like XML or JSON, with some prescribed ontology for some properties, as far as I recall. `pycifrw` deals with the container format, but not the contents of the files.

2020-01-26 16:40 UTC, bdice commented
@klarh I think replacing the string and creating a test for that is a fine compromise if the other files aren't licensed in a compatible way. Thanks!

2020-01-27 16:25 UTC, lyrivera approved these changes
LGTM

2020-01-27 18:24 UTC, bdice approved these changes
Ready to merge. 🥇

2020-01-27 20:26 UTC, merged