Update GetarFileReader to use the last index present for each quantity.
glotzerlab/garnett pull request #148
Opened 2020-02-28 23:36 UTC by klarh

## Description

This change makes it possible to properly read files that use "ragged"
storage of some quantities, for example changing particle shapes or
charges with a different period than positions are recorded at.

It does this by returning the largest index less than or equal to the corresponding position index for each dynamic quantity.

## Motivation and Context
This fixes the common occurrence in shape-changing simulations, for example, when positions are stored at a different frequency than shape information.

## How Has This Been Tested?

I added a test to ensure that the behavior works as expected.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds or improves functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update

Previously these files were unreadable, so it shouldn't hurt backwards compatibility.

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/glotzerlab/garnett/blob/master/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] I have updated the documentation (if relevant).
- [x] I have added tests that cover my changes (if relevant).
- [x] All new and existing tests passed.
- [x] I have updated the [credits](https://github.com/glotzerlab/garnett/blob/master/doc/credits.rst).
- [x] I have updated the [Changelog](https://github.com/glotzerlab/garnett/blob/master/changelog.rst).

2020-02-28 23:39 UTC, bdice requested changes
@klarh It looks like this PR may conflict with #147. Do you think we should rebase this on top of that PR? We're aiming to merge #147 in the near future.

2020-02-28 23:44 UTC, bdice commented on tests/test_getarfilereader.py
> +                if frame%2:
```suggestion
                if frame % 2:
```

2020-02-29 00:04 UTC, klarh commented
@bdice I can do that. Should I make the PR be to merge this into `api-hoomd-types`?

2020-02-29 00:18 UTC, bdice commented
> @bdice I can do that. Should I make the PR be to merge this into `api-hoomd-types`?

Yes please!

2020-03-02 16:18 UTC, lyrivera approved these changes
Looks good to me.

2020-03-10 21:41 UTC, bdice approved these changes
LGTM!

2020-03-10 21:41 UTC, merged